### PR TITLE
php 8.0 compatibility

### PR DESCRIPTION
**Pull request by syteknet-core**

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Hey @syteknet-core, thank you for this PR. Could you rebase your PR on master and do a `composer update --lock -W` so that the lock file is also up to date?

**Comment by syteknet-core** [comment]
@WyriHaximus thanks for the info. The PR is updated as requested!

**Comment by WyriHaximus** [comment]
@syteknet-core Thanks! FYI Also in the progress of updating some dependencies before I'm tagging a new release with this

**Comment by WyriHaximus** [comment]
@syteknet-core [`4.1.0`](https://github.com/WyriHaximus/HtmlCompress/releases/tag/4.1.0) is out with PHP 8 support

**Comment by syteknet-core** [comment]
@WyriHaximus thanks for the effort! right now a "composer update" on php 8.0.0 still fails due to a dependency
```
- wyrihaximus/js-compress 2.0.1 requires php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.
- wyrihaximus/html-compress 4.1.0 requires wyrihaximus/js-compress ^2.0.1 -> satisfiable by wyrihaximus/js-compress[2.0.1].
```

[this PR](https://github.com/WyriHaximus/php-js-compress/pull/46) takes care of it!

**Comment by WyriHaximus** [comment]
Hold on while I go facepalm myself 😂

**Comment by WyriHaximus** [comment]
@syteknet-core Should work now https://github.com/WyriHaximus/php-js-compress/releases/tag/2.0.2

**Comment by WyriHaximus** [comment]
FYI: https://github.com/WyriHaximus/HtmlCompress/issues/114

**Pull request merged**
